update:
	cd ../ && make clean
	cd ../ && git pull

install:
	cd ../ && make install

start:
	cd ../ && make start

stop:
	cd ../ && make stop

restart: stop start

shutdown:
	cd ../ && make stop_updater
